FROM ruby:3.2.8

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  postgresql-client \
  vim \
  libyaml-dev

WORKDIR /app

RUN gem install bundler:2.5.0
COPY Gemfile ./
RUN bundle lock --add-platform x86_64-linux
RUN bundle install
COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]