default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

development:
  <<: *default
  database: banking_api_development

test:
  <<: *default
  database: banking_api_test

production:
  <<: *default
  database: banking_api_production
  username: banking_api
  password: <%= ENV["BANKING_API_DATABASE_PASSWORD"] %>